{
 "title": "Solar Panels",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lifetime Generation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energytotal\")\r\n  |> last()\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Generation Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energytoday\")\r\n  |> last()\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Worktime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalworktime\")\r\n  |> last()\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "billed = from(bucket: \"nodered\")\r\n  |> range(start: -2y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meterreadings\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"billing\"] == \"yes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"offpeak\" or r[\"_field\"] == \"peak_generated\" or r[\"_field\"] == \"peak_used\")\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\",\"_stop\",\"billing\",\"_measurement\"])\r\n\r\ncurrent = from(bucket: \"nodered\")\r\n  |> range(start: -2y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meterreadings\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"billing\"] == \"no\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"offpeak\" or r[\"_field\"] == \"peak_generated\" or r[\"_field\"] == \"peak_used\")\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\",\"_stop\",\"billing\",\"_measurement\"])\r\n\r\njoin(tables: {billed: billed, current: current}, on: [\"type\"])\r\n  |>  map(fn: (r) => ({ r with balance: -(r.peak_used_current-r.peak_used_billed)+(r.peak_generated_current-r.peak_generated_billed) }))  "
    }
   ]
  },
  {
   "title": "Balance (estimated)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "billed = from(bucket: \"nodered\")\r\n  |> range(start: -2y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meterreadings\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"billing\"] == \"yes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"offpeak\" or r[\"_field\"] == \"peak_generated\" or r[\"_field\"] == \"peak_used\")\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\",\"_stop\",\"billing\",\"_measurement\"])\r\n\r\ncurrent = from(bucket: \"nodered\")\r\n  |> range(start: -2y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meterreadings\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"billing\"] == \"no\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"offpeak\" or r[\"_field\"] == \"peak_generated\" or r[\"_field\"] == \"peak_used\")\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\",\"_stop\",\"billing\",\"_measurement\"])\r\n\r\nmeterreadings = join(tables: {billed: billed, current: current}, on: [\"type\"])\r\n  |> map(fn: (r) => ({ r with balance: -(r.peak_used_current-r.peak_used_billed)+(r.peak_generated_current-r.peak_generated_billed) }))\r\n  |> map(fn: (r) => ({ r with join: 1 }))\r\n\r\n// Get the time for the last meter reading\r\ncurrent_time = from(bucket: \"nodered\")\r\n  |> range(start: -2y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"meterreadings\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"electricity\")\r\n  |> filter(fn: (r) => r[\"billing\"] == \"no\")\r\n  |> last()\r\n  |> tableFind(fn: (key) => key._field == \"offpeak\")\r\n  |> getRecord(idx: 0)\r\n\r\n// Get the usage from Shelly before the meter reading\r\nold_usage = from(bucket: \"nodered\")\r\n  |> range(start: -2y, stop:current_time._time)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"house_phase0\" or r[\"device\"] == \"house_phase1\" or r[\"device\"] == \"house_phase2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\" or r[\"_field\"] == \"total_returned\")\r\n  |> last()\r\n  |> pivot(rowKey: [\"_measurement\"], columnKey: [\"device\", \"_field\"], valueColumn: \"_value\")\r\n\r\n// Get the latest usage from Shelly\r\ncurrent_usage = from(bucket: \"nodered\")\r\n  |> range(start: -1w)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"house_phase0\" or r[\"device\"] == \"house_phase1\" or r[\"device\"] == \"house_phase2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\" or r[\"_field\"] == \"total_returned\")\r\n  |> last()\r\n  |> pivot(rowKey: [\"_measurement\"], columnKey: [\"device\", \"_field\"], valueColumn: \"_value\")\r\n\r\n// Combine the tables containing the Shelly readings and calculate the combined difference\r\nshelly = join(tables: {old_usage: old_usage, current_usage: current_usage}, on: [\"_measurement\"])\r\n  |>  map(fn: (r) => ({ r with shelly_usage: (-(r.house_phase0_total_current_usage-r.house_phase0_total_old_usage)-\r\n    (r.house_phase1_total_current_usage-r.house_phase1_total_old_usage)-\r\n    (r.house_phase2_total_current_usage-r.house_phase2_total_old_usage)+\r\n    (r.house_phase0_total_returned_current_usage-r.house_phase0_total_returned_old_usage)+\r\n    (r.house_phase1_total_returned_current_usage-r.house_phase1_total_returned_old_usage)+\r\n    (r.house_phase2_total_returned_current_usage-r.house_phase2_total_returned_old_usage)\r\n    )/1000.0 }))\r\n  |> map(fn: (r) => ({ r with join: 1 }))\r\n\r\njoin(tables: {meterreadings : meterreadings , shelly: shelly}, on: [\"join\"])\r\n  |>  map(fn: (r) => ({ r with balance_est: r.shelly_usage+r.balance}))\r\n  |> keep(columns: [\"balance_est\"])"
    }
   ]
  },
  {
   "title": "Power Generation Today",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "starttime = from(bucket: \"nodered\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outputpower\")\r\n  |> group()\r\n  |> first()\r\n  |> group(columns: [\"_field\", \"_measurement\"], mode:\"by\")\r\n  |> tableFind(fn: (key) => key._field == \"outputpower\")\r\n  |> getRecord(idx: 0)\r\n\r\nendtime = from(bucket: \"nodered\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outputpower\")\r\n  |> group()\r\n  |> last()\r\n  |> group(columns: [\"_field\", \"_measurement\"], mode:\"by\")\r\n  |> tableFind(fn: (key) => key._field == \"outputpower\")\r\n  |> getRecord(idx: 0)\r\n\r\nfrom(bucket: \"nodered\")\r\n  |> range(start: starttime._time, stop: endtime._time)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outputpower\")"
    }
   ]
  },
  { "title": "Garage Inverter (3kW)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"garage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status_text\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Derate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"garage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"deratingmode_text\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Fault",
   "type": "stat",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"garage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"faultcode_text\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"garage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energytoday\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Garage Inverter",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"garage\")\r\n  |> filter(fn: (r) => contains(value: r[\"_field\"], set: [\"pv2current\",\"pv2voltage\",\"solarpower\",\"pv2power\",\"outputpower\",\"gridfrequency\",\"gridvoltage\",\"tempinverter\",\"tempipm\"]))\r\n//  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n//  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lifetime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"garage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energytotal\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Worktime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"garage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalworktime\")\r\n  |> last()"
    }
   ]
  },
  { "title": "Small Inverter (1kW)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"small\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status_text\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Derate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"small\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"deratingmode_text\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Fault",
   "type": "stat",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"small\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"faultcode_text\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"small\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energytoday\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Small Inverter",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"small\")\r\n  |> filter(fn: (r) => contains(value: r[\"_field\"], set: [\"pv2current\",\"pv2voltage\",\"solarpower\",\"pv2power\",\"outputpower\",\"gridfrequency\",\"gridvoltage\",\"tempinverter\",\"tempipm\"]))\r\n//  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n//  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lifetime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"small\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energytotal\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Worktime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"small\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalworktime\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Old Inverter (3kW)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"old\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status_text\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Fault",
   "type": "stat",
   "gridPos": { "h": 2, "w": 13, "x": 4, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"old\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"faultcode_text\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"old\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energytoday\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Old Inverter",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"old\")\r\n  |> filter(fn: (r) => contains(value: r[\"_field\"], set: [\"pv2current\",\"pv2voltage\",\"solarpower\",\"pv2power\",\"outputpower\",\"gridfrequency\",\"gridvoltage\",\"tempinverter\"]))\r\n//  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n//  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lifetime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"old\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energytotal\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Worktime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"old\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalworktime\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Total Generation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "query": "garagedata = from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"garage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outputpower\")\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n\r\n\r\nsmalldata = from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"small\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outputpower\")\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n\r\nolddata = from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solar\")\r\n  |> filter(fn: (r) => r[\"inverter\"] == \"old\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outputpower\")\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n\r\nunion(tables: [garagedata,smalldata,olddata])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"_time\", \"_measurement\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"inverter\"], valueColumn: \"outputpower\")\r\n  |> group()\r\n  |> map(fn: (r) => ({r with garage: if exists r.garage then r.garage else 0.0})) \r\n  |> map(fn: (r) => ({r with small: if exists r.small then r.small else 0.0}))  \r\n  |> map(fn: (r) => ({r with old: if exists r.old then r.old else 0.0}))   \r\n  |> map(fn: (r) => ({r with _value: r.garage+r.old+r.small}))\r\n  |> drop(columns: [\"garage\",\"old\",\"small\"])"
    }
   ]
  },
  {
   "title": "House Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"house_phase0\" or r[\"device\"] == \"house_phase1\" or r[\"device\"] == \"house_phase2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\" or r[\"_field\"] == \"returned_energy\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: r.energy-r.returned_energy}))\r\n  |> drop(columns: [\"_start\", \"_stop\",\"energy\",\"returned_energy\"])"
    }
   ]
  }
 ]
}